version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - '3002:3002'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
      - user-service
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002

  frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3003:3000'
    depends_on:
      - gateway-service

volumes:
  mongo-data:
